# Nom du site
site_name: Test Site
site_url: https://test.jefe.ovh

# URL du dépôt GitHub
repo_url: https://github.com/Jefedi/Test-mcdocs.git

# Nom du dépôt GitHub
repo_name: Jefedi/test-mcdocs


# Navigation du site
nav:
  - Accueil:
    - blog/index.md

# Paramètres de la documentation
# Thème du site
theme:
  language: fr
  name: material
  logo: assets/dyanasty8.png
  icon:
    repo: fontawesome/brands/github
    admonition:
      alert: material/alert
  features:
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    # - navigation.footer
    # - navigation.tabs
    # - navigation.tabs.sticky
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions Markdown
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde


plugins:
  - search
  - tags
  - glightbox
  - git-revision-date-localized:
      type: timeago
  - meta
  - blog:
      enabled: true
      post_date_format: long
      post_url_date_format: yyyy/MM
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags



# Paramètres supplémentaires
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/JGudwhRJ3t
  version:
    provider: Jefe
  consent:
    title: Consentement aux cookies
    actions:
      - accept
      - reject
      - manage
    description: >- 
      Nous utilisons des cookies pour reconnaître vos visites répétées et vos préférences, ainsi que pour mesurer l'efficacité de notre documentation et savoir si les utilisateurs trouvent ce qu'ils recherchent. En donnant votre consentement, vous nous aidez à améliorer notre documentation.
  copyright: Copyright &copy; 2025 - 2025 Jefe
  generator: false

# Schéma pour le serveur de langage YAML
yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json



