# Nom du site
site_name: Test Site
site_url: https://test.jefe.ovh

# URL du dépôt GitHub
repo_url: https://github.com/Jefedi/Test-mcdocs.git

# Nom du dépôt GitHub
repo_name: Jefedi/test-mcdocs


# Navigation du site
nav:
  - Blog:
    - blog/index.md


# Paramètres de la documentation
# Thème du site
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: indigo

extra:
  annotations:
    json:
      icon: material/code-json
      title: JSON
    yaml:
      icon: material/file-code
      title: YAML


# Extensions Markdown
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde


plugins:
  - search
  - tags
  - glightbox
  - git-revision-date-localized:
      type: timeago
  - meta
  - blog:
      enabled: true
      post_date_format: long
      post_url_date_format: yyyy/MM
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags


# Schéma pour le serveur de langage YAML
yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json